version: '3'
services:
  kaggle-learn:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    container_name: kaggle-learn-container
    devices:
      - "/dev/video0:/dev/video0"
    privileged: true
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]

  label-studio:
    image: heartexlabs/label-studio:latest
    container_name: label-studio-container
    ports:
      - "8080:8080"  # Label Studio UI accessible at http://localhost:8080
    volumes:
      - ./label_data:/label-studio/data
    environment:
      - LABEL_STUDIO_DISABLE_ANALYTICS=true
