version: '3.8'

services:
  kaggle-learn:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    container_name: kaggle-learn-container
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]