@base_url = http://localhost:5000

### 🏠 Home Route
GET  {{base_url}}/
Content-Type: application/json

### Status Route
GET {{base_url}}/status
Content-Type: application/json

### Welcome Route
GET {{base_url}}/greet?name=Ali
Content-Type: application/json

### Message Route
POST {{base_url}}/message
Content-Type: application/json
Accept: application/json

{
    "name":"hacked"
}

### DELETE Route
DELETE {{base_url}}/delete/1